### ISSUE TITLE
Ruby Kaja 2015を選ぶ

### ISSUE THREAD

**Issue by chezou** [kawasakirb/meetups#34]
Rubyコミュニティで活躍している人を選ぶRuby Kaja 2015を選びます！
詳細は以下をお読みください〜。
http://kaja.rubyist.net/2015/about

自薦他薦問わないので、人と理由を共にお書きください！
ちなみに、 chezou は昨年受賞したのでそれ以外の方をお願いします〜

昨年の受賞者の例: http://kaja.rubyist.net/2014/kaja

**Comment by Peranikov** [comment]
推薦します〜

ぺけみさおさん https://twitter.com/xmisao
理由: BestGems、xAnimeDBなどRubyによるプロダクトを複数構築・運営しているから

http://bestgems.org/
http://animedb.xmisao.com/

**Comment by ngzm** [comment]
初期の頃から引っ張ってもらってる とくださんがいいと思いました。

あと、ぺけみさおさんも、ぺらさんもいいですね。。

**Comment by chezou** [comment]
残念ながら、今年のRubyKajaは中止となった旨連絡が来ました。
今後は不定期で開催予定とのことです。
